
package calcws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculatorImpl", targetNamespace = "http://calcws")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculatorImpl {


    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "subReturn", targetNamespace = "http://calcws")
    @RequestWrapper(localName = "sub", targetNamespace = "http://calcws", className = "calcws.Sub")
    @ResponseWrapper(localName = "subResponse", targetNamespace = "http://calcws", className = "calcws.SubResponse")
    public double sub(
        @WebParam(name = "a", targetNamespace = "http://calcws")
        double a,
        @WebParam(name = "b", targetNamespace = "http://calcws")
        double b);

    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "mulReturn", targetNamespace = "http://calcws")
    @RequestWrapper(localName = "mul", targetNamespace = "http://calcws", className = "calcws.Mul")
    @ResponseWrapper(localName = "mulResponse", targetNamespace = "http://calcws", className = "calcws.MulResponse")
    public double mul(
        @WebParam(name = "a", targetNamespace = "http://calcws")
        double a,
        @WebParam(name = "b", targetNamespace = "http://calcws")
        double b);

    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "addReturn", targetNamespace = "http://calcws")
    @RequestWrapper(localName = "add", targetNamespace = "http://calcws", className = "calcws.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://calcws", className = "calcws.AddResponse")
    public double add(
        @WebParam(name = "a", targetNamespace = "http://calcws")
        double a,
        @WebParam(name = "b", targetNamespace = "http://calcws")
        double b);

    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "divReturn", targetNamespace = "http://calcws")
    @RequestWrapper(localName = "div", targetNamespace = "http://calcws", className = "calcws.Div")
    @ResponseWrapper(localName = "divResponse", targetNamespace = "http://calcws", className = "calcws.DivResponse")
    public double div(
        @WebParam(name = "a", targetNamespace = "http://calcws")
        double a,
        @WebParam(name = "b", targetNamespace = "http://calcws")
        double b);

}
